### PR TITLE
Prepare v2.0.5

### PR DESCRIPTION
**Pull request by sunhailin-Leo**
### version 2.0.5

***Add***
* [issue#2259](https://github.com/pyecharts/pyecharts/issues/2259) 增加 `GeoItem` 用来兼容仅传入经纬度数据的模式
* [issue#2254](https://github.com/pyecharts/pyecharts/issues/2254) 增加对 Numpy 和 Pandas 非原生数据结构作为数据入参的错误提示。

**Updated**
* [issue#2227](https://github.com/pyecharts/pyecharts/issues/2227) 增加部分 `Sunburst` 的配置
* [issue#2263](https://github.com/pyecharts/pyecharts/issues/2263) 所有的图表增加 `Emphasis` 的配置
* [issue#2240](https://github.com/pyecharts/pyecharts/issues/2240) 更新 Radar 图的配置
* [issue#2286](https://github.com/pyecharts/pyecharts/pull/2286) 更新 VisualMapOpts 的配置

**Fixed**
* [issue#2236](https://github.com/pyecharts/pyecharts/issues/2236) 修复 `LegendOpts` 的 `border_width` 在特定配置下导致的样式异常问题
* [issue#2264](https://github.com/pyecharts/pyecharts/issues/2264) 修复 `Grid` 下多个 `DataZoomOpts` 失效的问题
* [issue#2265](https://github.com/pyecharts/pyecharts/issues/2265) 修复 `Sankey` 的配置错误问题

---

### version 2.0.5

***Add***
* [issue#2259](https://github.com/pyecharts/pyecharts/issues/2259) Add `GeoItem` for compatibility with incoming latitude/longitude data only.
* [issue#2254](https://github.com/pyecharts/pyecharts/issues/2254) Add an error alert for Numpy and Pandas non-native data structures as data inputs.

**Updated**
* [issue#2227](https://github.com/pyecharts/pyecharts/issues/2227) Update the part of `Sunburst` configuration.
* [issue#2263](https://github.com/pyecharts/pyecharts/issues/2263) Update `Emphasis` configuration to all charts.
* [issue#2240](https://github.com/pyecharts/pyecharts/issues/2240) Update the part of `Radar` configuration.
* [issue#2286](https://github.com/pyecharts/pyecharts/pull/2286) Update the part of `VisualMapOpts` configuration.

**Fixed**
* [issue#2236](https://github.com/pyecharts/pyecharts/issues/2236) Fix style anomalies in `LegendOpts.border_width` caused by certain configurations.
* [issue#2264](https://github.com/pyecharts/pyecharts/issues/2264) Fix multiple `DataZoomOpts` failures under `Grid.
* [issue#2265](https://github.com/pyecharts/pyecharts/issues/2265) Fix `Sankey` configuration bug.

### CODE REVIEW

**Review by chenjiandongx — DISMISSED** [review]

**Comment by yambor** [comment]
怎么下载pyecharts 2.0.5在电脑上啊 小白真诚请教谢谢！！

**Comment by sunhailin-Leo** [comment]
> 怎么下载pyecharts 2.0.5在电脑上啊 小白真诚请教谢谢！！

都还没 release 呢

**Comment by greatofdream** [comment]
> 都还没 release 呢

Release的日程有预计时间吗？

**Comment by sunhailin-Leo** [comment]
> > 都还没 release 呢
> 
> Release的日程有预计时间吗？

本周内 release 哈~

**Pull request merged**
