### PR TITLE
Improvement: replace extra_context with **kwargs

### PR DESCRIPTION
**Pull request by chfw**
passing dictionary as keyword arguments.

### CODE REVIEW

**Comment by chenjiandongx** [comment]
测试没过

**Comment by kinegratii** [comment]
**Feature**

I write the code following Django style before,it is OK to change to Flask Style.
[Flask Style](http://flask.pocoo.org/docs/0.12/api/#flask.render_template):
```
flask.render_template(template_name_or_list, **context)
```
[Django Style](https://docs.djangoproject.com/es/2.0/topics/http/shortcuts/#render)

```
render(request, template_name, context=None, content_type=None, status=None, using=None)
```

**Advice**

- Function comment should also be updated.
- Please merge this PR into *dev* branch first

**Comment by chfw** [comment]
@kinegratii , your comments are interesting. I didn't realized that mine are in Flask style. And it is true that I used Flask a lot and obviously you are a django developer. Flask style looks compact. But I do not want to say it is better than django style. Both are different choices in naming things.

I would drop this PR request because @chenjiandongx uses django-style function parameters and for pycharm, it works better.

**Comment by chfw** [comment]
I think that applies to template rendering only. 

with **kwargs, I can freely put an extra parameter: delay=1, but with extra_context=.. , I need to do `extra_context={'delay': 1}`.

**Comment by chfw** [comment]
screen shot 2018-03-14 at 23 36 37

**Pull request closed without merging**
